### ISSUE TITLE
Homebridge Plugin?

### ISSUE THREAD

**Issue by latetedemelon** [joeshaw/powerley-energybridge-homecontrol#2]
Hi Joe,

Any thought to turning this into a homebridge plugin?  Just wanted to see if it was on your radar.

https://github.com/homebridge/homebridge-plugin-template

Cheers

Rob

**Comment by joeshaw** [comment]
@latetedemelon I am not a Homebridge user but my understanding is that the plugins have to be written in Javascript, and this project is written in Go.  That means a total rewrite, and not something I'm interested in doing.  But you could run this alongside an existing Homebridge installation without any problems, but you wouldn't get whatever additional integration Homebridge gives you.

There may be existing Homebridge plugins that do what you want.  Communication with the energy bridge is via MQTT, so that's what you want to search for.  One possibility is https://github.com/uebelack/homebridge-mqtt-power-consumption.  There may be others.  Good luck!

**Comment by latetedemelon** [comment]
No worries, I'll take a look thanks.

FYI, this repo seems to have a full list of topics if you're interested:

https://github.com/timothyf/dte-eb-connect/blob/master/src/config-topics.js
